### ISSUE TITLE
Unexpected token '$'

### ISSUE THREAD

**Issue by sevenmaxis** [kddeisz/vernacular-ast#10]
```
$ rake test                                                                                                                                     
racc: /var/folders/7y/7f0kz5bd5ndchl32n6zv8cnh0000gn/T/parser-20181204-84095-171tog0.y: parser-20181204-84095-171tog0.y:9616: unexpected token '$'
Traceback (most recent call last):
        15: from /Users/megas/.rbenv/versions/2.6.0-preview3/lib/ruby/gems/2.6.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:2:in `<main>'
        14: from /Users/megas/.rbenv/versions/2.6.0-preview3/lib/ruby/gems/2.6.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:2:in `require'
        13: from /Users/megas/Work/ruby/vernacular-ast/lib/vernacular/ast.rb:22:in `load_iseq'
        12: from /Users/megas/.rbenv/versions/2.6.0-preview3/lib/ruby/gems/2.6.0/gems/vernacular-1.0.0/lib/vernacular.rb:23:in `load_iseq'
        11: from /Users/megas/.rbenv/versions/2.6.0-preview3/lib/ruby/gems/2.6.0/gems/vernacular-1.0.0/lib/vernacular/source_file.rb:38:in `load_iseq'
        10: from /Users/megas/.rbenv/versions/2.6.0-preview3/lib/ruby/gems/2.6.0/gems/vernacular-1.0.0/lib/vernacular/source_file.rb:30:in `load'
         9: from /Users/megas/.rbenv/versions/2.6.0-preview3/lib/ruby/gems/2.6.0/gems/vernacular-1.0.0/lib/vernacular/source_file.rb:15:in `dump'
         8: from /Users/megas/.rbenv/versions/2.6.0-preview3/lib/ruby/gems/2.6.0/gems/vernacular-1.0.0/lib/vernacular.rb:68:in `modify'
         7: from /Users/megas/.rbenv/versions/2.6.0-preview3/lib/ruby/gems/2.6.0/gems/vernacular-1.0.0/lib/vernacular.rb:68:in `each'
         6: from /Users/megas/.rbenv/versions/2.6.0-preview3/lib/ruby/gems/2.6.0/gems/vernacular-1.0.0/lib/vernacular.rb:69:in `block in modify'
         5: from /Users/megas/Work/ruby/vernacular-ast/lib/vernacular/ast/modifier.rb:49:in `modify'
         4: from /Users/megas/Work/ruby/vernacular-ast/lib/vernacular/ast/ast_parser.rb:31:in `parser'
         3: from /Users/megas/Work/ruby/vernacular-ast/lib/vernacular/ast/ast_parser.rb:17:in `parser'
         2: from /Users/megas/Work/ruby/vernacular-ast/lib/vernacular/ast/ast_parser.rb:90:in `write_parser'
         1: from /Users/megas/Work/ruby/vernacular-ast/lib/vernacular/ast/ast_parser.rb:57:in `compile_parser'
/Users/megas/Work/ruby/vernacular-ast/lib/vernacular/ast/ast_parser.rb:57:in `read': No such file or directory @ rb_sysopen - /Users/megas/Work/ruby/vernacular-ast/lib/vernacular/ast/parser.rb (Errno::ENOENT)
rake aborted!
Command failed with status (1)

Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by kddeisz** [comment]
@sevenmaxis did you end up figuring out what went wrong?
